version: '3.2'

services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - devhelm

  database:
    image: timescale/timescaledb-ha:pg17
    environment:
      - POSTGRES_DB=${PSQGL_DATABASE_NAME}
      - POSTGRES_USER=${PSQGL_DATABASE_USER}
      - POSTGRES_PASSWORD=${PSQGL_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/home/postgres/pgdata/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devhelm

  redis:
    image: redis:5-alpine
    networks:
      - devhelm
    ports:
      - "6379:6379"

  php-fpm:
    image: billabear/ubuntu-php-fpm:8.4
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=pgsql://${PSQGL_DATABASE_USER}:${PSQGL_DATABASE_PASSWORD}@database:5432/${PSQGL_DATABASE_NAME}
    volumes:
      - .:/var/www
    networks:
      - devhelm

  nginx:
    image: getparthenon/ubuntu-nginx:21.04
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - devhelm

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  devhelm:
    driver: bridge

volumes:
  db-data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
