name: MCP Go CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-go.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-go.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Download dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -mod=vendor ./...

      - name: Test
        run: |
          go test -mod=vendor ./... -v

      - name: Vet
        run: |
          go vet ./...
