name: Plugin CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'plugin/**'
      - '.github/workflows/plugin-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'plugin/**'
      - '.github/workflows/plugin-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Gradle 8.7 (temporary for wrapper generation)
        run: |
          GRADLE_VERSION=8.7
          curl -sL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle.zip
          unzip -q gradle.zip -d $HOME/.gradle-dists
          echo "GRADLE_HOME=$HOME/.gradle-dists/gradle-${GRADLE_VERSION}" >> $GITHUB_ENV
          echo "$HOME/.gradle-dists/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH

      - name: Generate/ensure Gradle Wrapper JAR
        run: |
          # Ensure the wrapper JAR exists so ./gradlew can be used reliably
          gradle --version
          gradle wrapper --gradle-version 8.7 --distribution-type all

      - name: Verify Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Verify Plugin
        run: ./gradlew verifyPlugin --stacktrace
