name: Plugin CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'plugin/**'
      - '.github/workflows/plugin-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'plugin/**'
      - '.github/workflows/plugin-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Verify Plugin
        run: ./gradlew verifyPlugin --stacktrace
