controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

parthenon_user_controllers:
    prefix: /app
    resource: ../vendor/parthenon/parthenon/src/User/Controller/
    type: attribute

parthenon_payments_controllers:
    prefix: /app
    resource: ../vendor/parthenon/parthenon/src/Billing/Controller/
    type: attribute
